{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "1e51ab9a",
   "metadata": {},
   "source": [
    "# Kerja Gaya Gesek\n",
    "\n",
    "Sparisoma Viridi<sup>1</sup>, Tim Pendukung<sup>2</sup> <br>\n",
    "Program Studi Sarjana Fisika, Institut Teknologi Bandung <br>\n",
    "Jalan Gensha 10, Bandung 40132, Indonesia <br>\n",
    "<sup>1</sup>dudung@gmail.com, https://github.com/dudung <br>\n",
    "<sup>2</sup>timpendukung@gmail.com, https://github.com/timpendukung\n",
    "\n",
    "Kerja yang dilakukan oleh gaya gesek merupakan bentuk kerja yang tidak diharapkan karena energi yang dikeluarkan, biasanya dalam bentuk panas atau bunyi yang dilepas ke lingkungan, tidak dapat dimanfaatkan lagi oleh sistem sehingga energi sistem berkurang."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aed2f31a",
   "metadata": {},
   "source": [
    "## Gerak benda di atas lantai mendatar kasar\n",
    "Sistem yang ditinjau adalah suatu benda yang bergerak di atas lantai mendatar kasar. Benda diberi kecepatan awal tertentu dan bergerak melambat sampai berhenti karena adanya gaya gesek kinetis antara benda dan lantai kasar."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "dc4acf61",
   "metadata": {},
   "source": [
    "## Parameter\n",
    "Beberapa parameter yang digunakan adalah seperti pada tabel berikut ini.\n",
    "\n",
    "Tabel <a name='tab1'>1</a>. Simbol beserta satuan dan artinya.\n",
    "\n",
    "Simbol | Satuan | Arti\n",
    ":- | :- | :-\n",
    "$t$ | s | waktu\n",
    "$v_0$ | m/s | kecepatan awal\n",
    "$x_0$ | m | posisi awal\n",
    "$v$ | m/s | kecepatan saat $t$\n",
    "$x$ | m | waktu saat $t$\n",
    "$a$ | m/s<sup>2</sup> | percepatan\n",
    "$\\mu_k$ | - | koefisien gesek kinetis\n",
    "$f_k$ | N | gaya gesek kinetis\n",
    "$m$ | kg | massa benda\n",
    "$F$ | N | total gaya yang bekerja\n",
    "$N$ | N | gaya normal\n",
    "$w$ | N | gaya gravitasi\n",
    "\n",
    "Simbol-simbol pada Tabel [1](#tab1) akan diberi nilai kemudian saat diimplementasikan dalam program."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "12457da3",
   "metadata": {},
   "source": [
    "## Persamaan\n",
    "Persamaan-persamaan yang akan digunakan adalah seperti dicantumkan pada bagian ini."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fb54dc5c",
   "metadata": {},
   "source": [
    "### Kinematika\n",
    "Hubungan antara antara kecepatan $v$, kecepatan awal $v_0$, percepatan $a$, dan waktu $t$ diberikan oleh\n",
    "\n",
    "<a name='eqn1'></a>\n",
    "\\begin{equation}\\label{eqn:kinematics-v-a-t}\\tag{1}\n",
    "v = v_0 + at.\n",
    "\\end{equation}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e52be88",
   "metadata": {},
   "source": [
    "Posisi benda $x$ bergantung pada posisi awal $x_0$, kecepatan awal $v_0$, percepatan $a$, dan waktu $t$ melalui hubungan\n",
    "\n",
    "<a name='eqn2'></a>\n",
    "\\begin{equation}\\label{eqn:kinematics-x-v-a-t}\\tag{2}\n",
    "x = x_0 + v_0 t + \\tfrac12 at^2.\n",
    "\\end{equation}\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3c8a08fa",
   "metadata": {},
   "source": [
    "Selain kedua persamaan sebelumnya, terdapat pula persamaan berikut\n",
    "\n",
    "<a name='eqn3'></a>\n",
    "\\begin{equation}\\label{eqn:kinematics-v-x-a}\\tag{3}\n",
    "v^2 = v_0^2 + 2a(x - x_0),\n",
    "\\end{equation}\n",
    "\n",
    "yang menghubungkan kecepatan $v$ dengan kecepatan awal $v_0$, percepatan $a$, dan jarak yang ditempuh $x - x_0$."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4fbcd3b6",
   "metadata": {},
   "source": [
    "### Dinamika\n",
    "Hukum Newton I menyatakan bahwa benda yang semula diam akan tetap diam dan yang semula bergerak dengan kecepatan tetap akan tetap bergerak dengan kecepatan tetap bila tidak ada gaya yang bekerja pada benda atau jumlah gaya-gaya yang bekerja sama dengan nol\n",
    "\n",
    "<a name='eqn4'></a>\n",
    "\\begin{equation}\\label{eqn:newtons-law-1}\\tag{4}\n",
    "\\sum F = 0.\n",
    "\\end{equation}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c237c502",
   "metadata": {},
   "source": [
    "Bila ada gaya yang bekerj pada benda bermassa $m$ atau jumlah gaya-gaya tidak nol\n",
    "\n",
    "<a name='eqn5'></a>\n",
    "\\begin{equation}\\label{eqn:newtons-law-2}\\tag{5}\n",
    "\\sum F = ma,\n",
    "\\end{equation}\n",
    "\n",
    "maka keadaan gerak benda akan berubah melalui percepatan $a$, dengan $m > 0$ dan $a \\ne 0$."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "79c05418",
   "metadata": {},
   "source": [
    "### Usaha\n",
    "Usaha oleh suatu gaya $F$ dengan posisi awal $x_0$ dan posisi akhir $x_0$ dapat diperoleh melalui\n",
    "\n",
    "<a name='eqn6'></a>\n",
    "\\begin{equation}\\label{eqn:work-1}\\tag{6}\n",
    "W = \\int_{x_0}^x F dx\n",
    "\\end{equation}\n",
    "\n",
    "atau dengan\n",
    "\n",
    "<a name='eqn7'></a>\n",
    "\\begin{equation}\\label{eqn:work-2}\\tag{7}\n",
    "W = \\Delta K\n",
    "\\end{equation}\n",
    "\n",
    "dengan $K$ adalah energi kinetik. Persamaan ([7](#eqn7)) akan memberikan gaya oleh semua gaya. Dengan demikian bila $F$ adalah satu-satunya gaya yang bekerja pada benda, maka persamaan ini akan menjadi Persamaan ([6](#eqn6))."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "44901d75",
   "metadata": {},
   "source": [
    "## Sistem\n",
    "Ilustrasi sistem perlu diberikan agar dapat terbayangan dan memudahkan penyelesaian masalah. Selain itu juga perlu disajikan diagram gaya-gaya yang bekerja pada benda."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8060fbca",
   "metadata": {},
   "source": [
    "### Ilustrasi\n",
    "Sistem yang benda bermassa $m$ bergerak di atas lantai kasar dapat digambarkan\n",
    "seperti berikut ini."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "479756b2",
   "metadata": {
    "tags": [
     "hide_input"
    ]
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<svg\n",
       "   width=\"320\"\n",
       "   height=\"140\"\n",
       "   viewBox=\"0 0 320 140.00001\"\n",
       "   id=\"svg2\"\n",
       "   version=\"1.1\"\n",
       "   inkscape:version=\"1.1.2 (b8e25be833, 2022-02-05)\"\n",
       "   sodipodi:docname=\"mass-horizontal-rough-surface.svg\"\n",
       "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n",
       "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n",
       "   xmlns=\"http://www.w3.org/2000/svg\"\n",
       "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n",
       "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n",
       "   xmlns:cc=\"http://creativecommons.org/ns#\"\n",
       "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n",
       "  <defs\n",
       "     id=\"defs4\">\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"marker11604\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"Arrow2Mend\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(-0.6)\"\n",
       "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
       "         id=\"path11602\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"Arrow2Mend\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"Arrow2Mend\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(-0.6)\"\n",
       "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
       "         id=\"path11361\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-3\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-1\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-35\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-0\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-0\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-4\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-37\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-9\" />\n",
       "    </marker>\n",
       "  </defs>\n",
       "  <sodipodi:namedview\n",
       "     id=\"base\"\n",
       "     pagecolor=\"#ffffff\"\n",
       "     bordercolor=\"#666666\"\n",
       "     borderopacity=\"1.0\"\n",
       "     inkscape:pageopacity=\"0.0\"\n",
       "     inkscape:pageshadow=\"2\"\n",
       "     inkscape:zoom=\"1.5\"\n",
       "     inkscape:cx=\"173\"\n",
       "     inkscape:cy=\"97.333333\"\n",
       "     inkscape:document-units=\"px\"\n",
       "     inkscape:current-layer=\"layer1\"\n",
       "     showgrid=\"false\"\n",
       "     inkscape:snap-bbox=\"false\"\n",
       "     inkscape:snap-global=\"false\"\n",
       "     units=\"px\"\n",
       "     showborder=\"true\"\n",
       "     inkscape:showpageshadow=\"true\"\n",
       "     borderlayer=\"false\"\n",
       "     inkscape:window-width=\"1366\"\n",
       "     inkscape:window-height=\"705\"\n",
       "     inkscape:window-x=\"-8\"\n",
       "     inkscape:window-y=\"-8\"\n",
       "     inkscape:window-maximized=\"1\"\n",
       "     inkscape:pagecheckerboard=\"0\">\n",
       "    <inkscape:grid\n",
       "       type=\"xygrid\"\n",
       "       id=\"grid970\" />\n",
       "  </sodipodi:namedview>\n",
       "  <metadata\n",
       "     id=\"metadata7\">\n",
       "    <rdf:RDF>\n",
       "      <cc:Work\n",
       "         rdf:about=\"\">\n",
       "        <dc:format>image/svg+xml</dc:format>\n",
       "        <dc:type\n",
       "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n",
       "      </cc:Work>\n",
       "    </rdf:RDF>\n",
       "  </metadata>\n",
       "  <g\n",
       "     inkscape:label=\"Layer 1\"\n",
       "     inkscape:groupmode=\"layer\"\n",
       "     id=\"layer1\"\n",
       "     transform=\"translate(0,-732.36216)\">\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"120.0725\"\n",
       "       y=\"759.6109\"\n",
       "       id=\"text2711-6-2-9\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2\"\n",
       "         x=\"120.0725\"\n",
       "         y=\"759.6109\"\n",
       "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
       "           style=\"font-style:italic\"\n",
       "           id=\"tspan9923\">v</tspan><tspan\n",
       "           style=\"font-size:65%;baseline-shift:sub\"\n",
       "           id=\"tspan1668\">0</tspan></tspan></text>\n",
       "    <path\n",
       "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM)\"\n",
       "       d=\"m 84.656156,757.55169 25.738704,1.3e-4\"\n",
       "       id=\"path11252\" />\n",
       "    <rect\n",
       "       style=\"fill:#ffffff;fill-opacity:1;stroke:#000000;stroke-width:1;stroke-linecap:round;stroke-opacity:1\"\n",
       "       id=\"rect1007\"\n",
       "       width=\"59\"\n",
       "       height=\"59\"\n",
       "       x=\"56.5\"\n",
       "       y=\"772.86218\"\n",
       "       rx=\"0\"\n",
       "       ry=\"0\" />\n",
       "    <path\n",
       "       style=\"fill:none;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n",
       "       d=\"m 20,832.86218 280,-2e-5\"\n",
       "       id=\"path1386\" />\n",
       "    <rect\n",
       "       style=\"fill:#ffffff;fill-opacity:1;stroke:#c8c8c8;stroke-width:0.5;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:2, 2;stroke-dashoffset:0;stroke-opacity:1\"\n",
       "       id=\"rect1007-2\"\n",
       "       width=\"59\"\n",
       "       height=\"59\"\n",
       "       x=\"225.16667\"\n",
       "       y=\"772.86218\"\n",
       "       rx=\"0\"\n",
       "       ry=\"0\" />\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#c8c8c8;fill-opacity:1;stroke:none\"\n",
       "       x=\"236.05922\"\n",
       "       y=\"759.6109\"\n",
       "       id=\"text2711-6-2-9-9\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-8\"\n",
       "         x=\"236.05922\"\n",
       "         y=\"759.6109\"\n",
       "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, ';fill:#c8c8c8;fill-opacity:1\"><tspan\n",
       "   style=\"font-style:italic;fill:#c8c8c8;fill-opacity:1\"\n",
       "   id=\"tspan9923-8\">v</tspan> = 0</tspan></text>\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"149.18359\"\n",
       "       y=\"824.54877\"\n",
       "       id=\"text2711-6-2-9-96\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-6\"\n",
       "         x=\"149.18359\"\n",
       "         y=\"824.54877\"\n",
       "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
       "   style=\"font-style:italic\"\n",
       "   id=\"tspan3028\">μ<tspan\n",
       "   style=\"font-size:65%;baseline-shift:sub\"\n",
       "   id=\"tspan3074\">k</tspan></tspan> &gt; 0</tspan></text>\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"79.505844\"\n",
       "       y=\"806.37714\"\n",
       "       id=\"text2711-6-2-9-2\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-84\"\n",
       "         x=\"79.505844\"\n",
       "         y=\"806.37714\"\n",
       "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">m</tspan></text>\n",
       "    <path\n",
       "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-37)\"\n",
       "       d=\"m 33.785239,770.82609 -1.3e-4,25.7387\"\n",
       "       id=\"path11252-5\" />\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"29.173132\"\n",
       "       y=\"759.45776\"\n",
       "       id=\"text2711-6-2-9-8\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-2\"\n",
       "         x=\"29.173132\"\n",
       "         y=\"759.45776\"\n",
       "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">g</tspan></text>\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"79.368446\"\n",
       "       y=\"849.21539\"\n",
       "       id=\"text2711-6-2-9-23\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-3\"\n",
       "         x=\"79.368446\"\n",
       "         y=\"849.21539\"\n",
       "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
       "           style=\"font-style:italic\"\n",
       "           id=\"tspan9923-0\">x</tspan><tspan\n",
       "           style=\"font-size:65%;baseline-shift:sub\"\n",
       "           id=\"tspan1668-9\">0</tspan></tspan></text>\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"250.91145\"\n",
       "       y=\"849.21539\"\n",
       "       id=\"text2711-6-2-9-23-0\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-3-0\"\n",
       "         x=\"250.91145\"\n",
       "         y=\"849.21539\"\n",
       "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
       "           style=\"font-style:italic\"\n",
       "           id=\"tspan9923-0-3\">x</tspan><tspan\n",
       "           style=\"font-size:65%;baseline-shift:sub\"\n",
       "           id=\"tspan1668-9-3\" /></tspan></text>\n",
       "  </g>\n",
       "</svg>\n",
       "\n",
       "<br/>\n",
       "\n",
       "Gambar <a name='fig1'>1</a>. Sistem benda bermassa $m$ begerak di atas lantai\n",
       "mendatar kasar dengan koefisien gesek kinetis $\\mu_k$.\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%html\n",
    "\n",
    "<svg\n",
    "   width=\"320\"\n",
    "   height=\"140\"\n",
    "   viewBox=\"0 0 320 140.00001\"\n",
    "   id=\"svg2\"\n",
    "   version=\"1.1\"\n",
    "   inkscape:version=\"1.1.2 (b8e25be833, 2022-02-05)\"\n",
    "   sodipodi:docname=\"mass-horizontal-rough-surface.svg\"\n",
    "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n",
    "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n",
    "   xmlns=\"http://www.w3.org/2000/svg\"\n",
    "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n",
    "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n",
    "   xmlns:cc=\"http://creativecommons.org/ns#\"\n",
    "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n",
    "  <defs\n",
    "     id=\"defs4\">\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"marker11604\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"Arrow2Mend\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(-0.6)\"\n",
    "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
    "         id=\"path11602\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"Arrow2Mend\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"Arrow2Mend\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(-0.6)\"\n",
    "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
    "         id=\"path11361\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-3\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-1\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-35\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-0\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-0\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-4\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-37\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-9\" />\n",
    "    </marker>\n",
    "  </defs>\n",
    "  <sodipodi:namedview\n",
    "     id=\"base\"\n",
    "     pagecolor=\"#ffffff\"\n",
    "     bordercolor=\"#666666\"\n",
    "     borderopacity=\"1.0\"\n",
    "     inkscape:pageopacity=\"0.0\"\n",
    "     inkscape:pageshadow=\"2\"\n",
    "     inkscape:zoom=\"1.5\"\n",
    "     inkscape:cx=\"173\"\n",
    "     inkscape:cy=\"97.333333\"\n",
    "     inkscape:document-units=\"px\"\n",
    "     inkscape:current-layer=\"layer1\"\n",
    "     showgrid=\"false\"\n",
    "     inkscape:snap-bbox=\"false\"\n",
    "     inkscape:snap-global=\"false\"\n",
    "     units=\"px\"\n",
    "     showborder=\"true\"\n",
    "     inkscape:showpageshadow=\"true\"\n",
    "     borderlayer=\"false\"\n",
    "     inkscape:window-width=\"1366\"\n",
    "     inkscape:window-height=\"705\"\n",
    "     inkscape:window-x=\"-8\"\n",
    "     inkscape:window-y=\"-8\"\n",
    "     inkscape:window-maximized=\"1\"\n",
    "     inkscape:pagecheckerboard=\"0\">\n",
    "    <inkscape:grid\n",
    "       type=\"xygrid\"\n",
    "       id=\"grid970\" />\n",
    "  </sodipodi:namedview>\n",
    "  <metadata\n",
    "     id=\"metadata7\">\n",
    "    <rdf:RDF>\n",
    "      <cc:Work\n",
    "         rdf:about=\"\">\n",
    "        <dc:format>image/svg+xml</dc:format>\n",
    "        <dc:type\n",
    "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n",
    "      </cc:Work>\n",
    "    </rdf:RDF>\n",
    "  </metadata>\n",
    "  <g\n",
    "     inkscape:label=\"Layer 1\"\n",
    "     inkscape:groupmode=\"layer\"\n",
    "     id=\"layer1\"\n",
    "     transform=\"translate(0,-732.36216)\">\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"120.0725\"\n",
    "       y=\"759.6109\"\n",
    "       id=\"text2711-6-2-9\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2\"\n",
    "         x=\"120.0725\"\n",
    "         y=\"759.6109\"\n",
    "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
    "           style=\"font-style:italic\"\n",
    "           id=\"tspan9923\">v</tspan><tspan\n",
    "           style=\"font-size:65%;baseline-shift:sub\"\n",
    "           id=\"tspan1668\">0</tspan></tspan></text>\n",
    "    <path\n",
    "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM)\"\n",
    "       d=\"m 84.656156,757.55169 25.738704,1.3e-4\"\n",
    "       id=\"path11252\" />\n",
    "    <rect\n",
    "       style=\"fill:#ffffff;fill-opacity:1;stroke:#000000;stroke-width:1;stroke-linecap:round;stroke-opacity:1\"\n",
    "       id=\"rect1007\"\n",
    "       width=\"59\"\n",
    "       height=\"59\"\n",
    "       x=\"56.5\"\n",
    "       y=\"772.86218\"\n",
    "       rx=\"0\"\n",
    "       ry=\"0\" />\n",
    "    <path\n",
    "       style=\"fill:none;stroke:#000000;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1\"\n",
    "       d=\"m 20,832.86218 280,-2e-5\"\n",
    "       id=\"path1386\" />\n",
    "    <rect\n",
    "       style=\"fill:#ffffff;fill-opacity:1;stroke:#c8c8c8;stroke-width:0.5;stroke-linecap:round;stroke-miterlimit:4;stroke-dasharray:2, 2;stroke-dashoffset:0;stroke-opacity:1\"\n",
    "       id=\"rect1007-2\"\n",
    "       width=\"59\"\n",
    "       height=\"59\"\n",
    "       x=\"225.16667\"\n",
    "       y=\"772.86218\"\n",
    "       rx=\"0\"\n",
    "       ry=\"0\" />\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#c8c8c8;fill-opacity:1;stroke:none\"\n",
    "       x=\"236.05922\"\n",
    "       y=\"759.6109\"\n",
    "       id=\"text2711-6-2-9-9\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-8\"\n",
    "         x=\"236.05922\"\n",
    "         y=\"759.6109\"\n",
    "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, ';fill:#c8c8c8;fill-opacity:1\"><tspan\n",
    "   style=\"font-style:italic;fill:#c8c8c8;fill-opacity:1\"\n",
    "   id=\"tspan9923-8\">v</tspan> = 0</tspan></text>\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"149.18359\"\n",
    "       y=\"824.54877\"\n",
    "       id=\"text2711-6-2-9-96\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-6\"\n",
    "         x=\"149.18359\"\n",
    "         y=\"824.54877\"\n",
    "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
    "   style=\"font-style:italic\"\n",
    "   id=\"tspan3028\">μ<tspan\n",
    "   style=\"font-size:65%;baseline-shift:sub\"\n",
    "   id=\"tspan3074\">k</tspan></tspan> &gt; 0</tspan></text>\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"79.505844\"\n",
    "       y=\"806.37714\"\n",
    "       id=\"text2711-6-2-9-2\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-84\"\n",
    "         x=\"79.505844\"\n",
    "         y=\"806.37714\"\n",
    "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">m</tspan></text>\n",
    "    <path\n",
    "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-37)\"\n",
    "       d=\"m 33.785239,770.82609 -1.3e-4,25.7387\"\n",
    "       id=\"path11252-5\" />\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"29.173132\"\n",
    "       y=\"759.45776\"\n",
    "       id=\"text2711-6-2-9-8\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-2\"\n",
    "         x=\"29.173132\"\n",
    "         y=\"759.45776\"\n",
    "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">g</tspan></text>\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"79.368446\"\n",
    "       y=\"849.21539\"\n",
    "       id=\"text2711-6-2-9-23\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-3\"\n",
    "         x=\"79.368446\"\n",
    "         y=\"849.21539\"\n",
    "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
    "           style=\"font-style:italic\"\n",
    "           id=\"tspan9923-0\">x</tspan><tspan\n",
    "           style=\"font-size:65%;baseline-shift:sub\"\n",
    "           id=\"tspan1668-9\">0</tspan></tspan></text>\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"250.91145\"\n",
    "       y=\"849.21539\"\n",
    "       id=\"text2711-6-2-9-23-0\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-3-0\"\n",
    "         x=\"250.91145\"\n",
    "         y=\"849.21539\"\n",
    "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
    "           style=\"font-style:italic\"\n",
    "           id=\"tspan9923-0-3\">x</tspan><tspan\n",
    "           style=\"font-size:65%;baseline-shift:sub\"\n",
    "           id=\"tspan1668-9-3\" /></tspan></text>\n",
    "  </g>\n",
    "</svg>\n",
    "\n",
    "<br/>\n",
    "\n",
    "Gambar <a name='fig1'>1</a>. Sistem benda bermassa $m$ begerak di atas lantai\n",
    "mendatar kasar dengan koefisien gesek kinetis $\\mu_k$."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7018f95c",
   "metadata": {},
   "source": [
    "Keadaan akhir benda, yaitu saat kecepatan $v = 0$ diberikan pada bagian kanan Gambar [1](#fig1) dengan warna abu-abu."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fb277d2b",
   "metadata": {},
   "source": [
    "### Diagram gaya\n",
    "Diagram gaya-gaya yang berja pada benda perlu dibuat berdasarkan informasi dari Gambar [1](#fig1) dan Tabel [1](#tab1), yang diberikan berikut ini."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1d265114",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<svg\n",
       "   width=\"320\"\n",
       "   height=\"200\"\n",
       "   viewBox=\"0 0 320 200.00001\"\n",
       "   id=\"svg2\"\n",
       "   version=\"1.1\"\n",
       "   inkscape:version=\"1.1.2 (b8e25be833, 2022-02-05)\"\n",
       "   sodipodi:docname=\"mass-horizontal-rough-surface-fbd.svg\"\n",
       "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n",
       "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n",
       "   xmlns=\"http://www.w3.org/2000/svg\"\n",
       "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n",
       "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n",
       "   xmlns:cc=\"http://creativecommons.org/ns#\"\n",
       "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n",
       "  <defs\n",
       "     id=\"defs4\">\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"marker11604\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"Arrow2Mend\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(-0.6)\"\n",
       "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
       "         id=\"path11602\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"Arrow2Mend\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"Arrow2Mend\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(-0.6)\"\n",
       "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
       "         id=\"path11361\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-3\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-1\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-35\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-0\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-0\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-4\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-37\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-9\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-9\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-8\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-9-3\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-8-3\" />\n",
       "    </marker>\n",
       "    <marker\n",
       "       style=\"overflow:visible\"\n",
       "       id=\"TriangleOutM-37-5\"\n",
       "       refX=\"0\"\n",
       "       refY=\"0\"\n",
       "       orient=\"auto\"\n",
       "       inkscape:stockid=\"TriangleOutM\"\n",
       "       inkscape:isstock=\"true\">\n",
       "      <path\n",
       "         transform=\"scale(0.4)\"\n",
       "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
       "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
       "         id=\"path11479-9-9\" />\n",
       "    </marker>\n",
       "  </defs>\n",
       "  <sodipodi:namedview\n",
       "     id=\"base\"\n",
       "     pagecolor=\"#ffffff\"\n",
       "     bordercolor=\"#666666\"\n",
       "     borderopacity=\"1.0\"\n",
       "     inkscape:pageopacity=\"0.0\"\n",
       "     inkscape:pageshadow=\"2\"\n",
       "     inkscape:zoom=\"1.2079428\"\n",
       "     inkscape:cx=\"159.36185\"\n",
       "     inkscape:cy=\"35.597712\"\n",
       "     inkscape:document-units=\"px\"\n",
       "     inkscape:current-layer=\"layer1\"\n",
       "     showgrid=\"false\"\n",
       "     inkscape:snap-bbox=\"false\"\n",
       "     inkscape:snap-global=\"false\"\n",
       "     units=\"px\"\n",
       "     showborder=\"true\"\n",
       "     inkscape:showpageshadow=\"true\"\n",
       "     borderlayer=\"false\"\n",
       "     inkscape:window-width=\"1366\"\n",
       "     inkscape:window-height=\"705\"\n",
       "     inkscape:window-x=\"-8\"\n",
       "     inkscape:window-y=\"-8\"\n",
       "     inkscape:window-maximized=\"1\"\n",
       "     inkscape:pagecheckerboard=\"0\">\n",
       "    <inkscape:grid\n",
       "       type=\"xygrid\"\n",
       "       id=\"grid970\" />\n",
       "  </sodipodi:namedview>\n",
       "  <metadata\n",
       "     id=\"metadata7\">\n",
       "    <rdf:RDF>\n",
       "      <cc:Work\n",
       "         rdf:about=\"\">\n",
       "        <dc:format>image/svg+xml</dc:format>\n",
       "        <dc:type\n",
       "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n",
       "      </cc:Work>\n",
       "    </rdf:RDF>\n",
       "  </metadata>\n",
       "  <g\n",
       "     inkscape:label=\"Layer 1\"\n",
       "     inkscape:groupmode=\"layer\"\n",
       "     id=\"layer1\"\n",
       "     transform=\"translate(0,-732.36216)\">\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"148.01953\"\n",
       "       y=\"766.72156\"\n",
       "       id=\"text2711-6-2-9-23\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-3\"\n",
       "         x=\"148.01953\"\n",
       "         y=\"766.72156\"\n",
       "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">N</tspan></text>\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"251.40584\"\n",
       "       y=\"806.94421\"\n",
       "       id=\"text2711-6-2-9\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2\"\n",
       "         x=\"251.40584\"\n",
       "         y=\"806.94421\"\n",
       "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
       "           style=\"font-style:italic\"\n",
       "           id=\"tspan9923\">v</tspan><tspan\n",
       "           style=\"font-size:65%;baseline-shift:sub\"\n",
       "           id=\"tspan1668\" /></tspan></text>\n",
       "    <path\n",
       "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM)\"\n",
       "       d=\"m 215.98949,804.88502 25.7387,1.3e-4\"\n",
       "       id=\"path11252\" />\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"153.68098\"\n",
       "       y=\"915.71051\"\n",
       "       id=\"text2711-6-2-9-2\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-84\"\n",
       "         x=\"153.68098\"\n",
       "         y=\"915.71051\"\n",
       "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">w</tspan></text>\n",
       "    <path\n",
       "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-37)\"\n",
       "       d=\"m 31.113403,791.97918 -1.3e-4,25.7387\"\n",
       "       id=\"path11252-5\" />\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"26.501303\"\n",
       "       y=\"780.6109\"\n",
       "       id=\"text2711-6-2-9-8\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-2\"\n",
       "         x=\"26.501303\"\n",
       "         y=\"780.6109\"\n",
       "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">g</tspan></text>\n",
       "    <rect\n",
       "       style=\"fill:#ffffff;fill-opacity:1;stroke:#000000;stroke-width:1;stroke-linecap:round;stroke-opacity:1\"\n",
       "       id=\"rect1007\"\n",
       "       width=\"59\"\n",
       "       height=\"59\"\n",
       "       x=\"130.5\"\n",
       "       y=\"792.86218\"\n",
       "       rx=\"0\"\n",
       "       ry=\"0\" />\n",
       "    <g\n",
       "       id=\"g1363\"\n",
       "       transform=\"translate(-6,20)\">\n",
       "      <path\n",
       "         style=\"fill:none;stroke:#ff0000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-9)\"\n",
       "         d=\"m 161.00001,831.69534 -45.73871,1.3e-4\"\n",
       "         id=\"path11252-4\" />\n",
       "      <path\n",
       "         style=\"fill:none;stroke:#0000ff;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-9-3)\"\n",
       "         d=\"m 160.79738,832.36215 -1.3e-4,-75.7387\"\n",
       "         id=\"path11252-4-6\" />\n",
       "    </g>\n",
       "    <path\n",
       "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-37-5)\"\n",
       "       d=\"m 159.99967,822.02879 3.4e-4,75.73871\"\n",
       "       id=\"path11252-5-0\" />\n",
       "    <text\n",
       "       xml:space=\"preserve\"\n",
       "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
       "       x=\"85.624084\"\n",
       "       y=\"854.51099\"\n",
       "       id=\"text2711-6-2-9-8-4\"><tspan\n",
       "         sodipodi:role=\"line\"\n",
       "         id=\"tspan2709-5-9-2-2-1\"\n",
       "         x=\"85.624084\"\n",
       "         y=\"854.51099\"\n",
       "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">f<tspan\n",
       "   style=\"font-size:65%;baseline-shift:sub\"\n",
       "   id=\"tspan2197\">k</tspan></tspan></text>\n",
       "  </g>\n",
       "</svg>\n",
       "\n",
       "<br>\n",
       "\n",
       "Gambar <a name='fig2'>2</a>. Diagram gaya-gaya yang bekerja pada benda\n",
       "bermassa $m$.\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%%html\n",
    "\n",
    "<svg\n",
    "   width=\"320\"\n",
    "   height=\"200\"\n",
    "   viewBox=\"0 0 320 200.00001\"\n",
    "   id=\"svg2\"\n",
    "   version=\"1.1\"\n",
    "   inkscape:version=\"1.1.2 (b8e25be833, 2022-02-05)\"\n",
    "   sodipodi:docname=\"mass-horizontal-rough-surface-fbd.svg\"\n",
    "   xmlns:inkscape=\"http://www.inkscape.org/namespaces/inkscape\"\n",
    "   xmlns:sodipodi=\"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd\"\n",
    "   xmlns=\"http://www.w3.org/2000/svg\"\n",
    "   xmlns:svg=\"http://www.w3.org/2000/svg\"\n",
    "   xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n",
    "   xmlns:cc=\"http://creativecommons.org/ns#\"\n",
    "   xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n",
    "  <defs\n",
    "     id=\"defs4\">\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"marker11604\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"Arrow2Mend\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(-0.6)\"\n",
    "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
    "         id=\"path11602\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"Arrow2Mend\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"Arrow2Mend\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(-0.6)\"\n",
    "         d=\"M 8.7185878,4.0337352 -2.2072895,0.01601326 8.7185884,-4.0017078 c -1.7454984,2.3720609 -1.7354408,5.6174519 -6e-7,8.035443 z\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:0.625;stroke-linejoin:round\"\n",
    "         id=\"path11361\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-3\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-1\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-35\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-0\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-0\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-4\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-37\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-9\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-9\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-8\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-9-3\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-8-3\" />\n",
    "    </marker>\n",
    "    <marker\n",
    "       style=\"overflow:visible\"\n",
    "       id=\"TriangleOutM-37-5\"\n",
    "       refX=\"0\"\n",
    "       refY=\"0\"\n",
    "       orient=\"auto\"\n",
    "       inkscape:stockid=\"TriangleOutM\"\n",
    "       inkscape:isstock=\"true\">\n",
    "      <path\n",
    "         transform=\"scale(0.4)\"\n",
    "         style=\"fill:context-stroke;fill-rule:evenodd;stroke:context-stroke;stroke-width:1pt\"\n",
    "         d=\"M 5.77,0 -2.88,5 V -5 Z\"\n",
    "         id=\"path11479-9-9\" />\n",
    "    </marker>\n",
    "  </defs>\n",
    "  <sodipodi:namedview\n",
    "     id=\"base\"\n",
    "     pagecolor=\"#ffffff\"\n",
    "     bordercolor=\"#666666\"\n",
    "     borderopacity=\"1.0\"\n",
    "     inkscape:pageopacity=\"0.0\"\n",
    "     inkscape:pageshadow=\"2\"\n",
    "     inkscape:zoom=\"1.2079428\"\n",
    "     inkscape:cx=\"159.36185\"\n",
    "     inkscape:cy=\"35.597712\"\n",
    "     inkscape:document-units=\"px\"\n",
    "     inkscape:current-layer=\"layer1\"\n",
    "     showgrid=\"false\"\n",
    "     inkscape:snap-bbox=\"false\"\n",
    "     inkscape:snap-global=\"false\"\n",
    "     units=\"px\"\n",
    "     showborder=\"true\"\n",
    "     inkscape:showpageshadow=\"true\"\n",
    "     borderlayer=\"false\"\n",
    "     inkscape:window-width=\"1366\"\n",
    "     inkscape:window-height=\"705\"\n",
    "     inkscape:window-x=\"-8\"\n",
    "     inkscape:window-y=\"-8\"\n",
    "     inkscape:window-maximized=\"1\"\n",
    "     inkscape:pagecheckerboard=\"0\">\n",
    "    <inkscape:grid\n",
    "       type=\"xygrid\"\n",
    "       id=\"grid970\" />\n",
    "  </sodipodi:namedview>\n",
    "  <metadata\n",
    "     id=\"metadata7\">\n",
    "    <rdf:RDF>\n",
    "      <cc:Work\n",
    "         rdf:about=\"\">\n",
    "        <dc:format>image/svg+xml</dc:format>\n",
    "        <dc:type\n",
    "           rdf:resource=\"http://purl.org/dc/dcmitype/StillImage\" />\n",
    "      </cc:Work>\n",
    "    </rdf:RDF>\n",
    "  </metadata>\n",
    "  <g\n",
    "     inkscape:label=\"Layer 1\"\n",
    "     inkscape:groupmode=\"layer\"\n",
    "     id=\"layer1\"\n",
    "     transform=\"translate(0,-732.36216)\">\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"148.01953\"\n",
    "       y=\"766.72156\"\n",
    "       id=\"text2711-6-2-9-23\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-3\"\n",
    "         x=\"148.01953\"\n",
    "         y=\"766.72156\"\n",
    "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">N</tspan></text>\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"251.40584\"\n",
    "       y=\"806.94421\"\n",
    "       id=\"text2711-6-2-9\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2\"\n",
    "         x=\"251.40584\"\n",
    "         y=\"806.94421\"\n",
    "         style=\"font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\"><tspan\n",
    "           style=\"font-style:italic\"\n",
    "           id=\"tspan9923\">v</tspan><tspan\n",
    "           style=\"font-size:65%;baseline-shift:sub\"\n",
    "           id=\"tspan1668\" /></tspan></text>\n",
    "    <path\n",
    "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM)\"\n",
    "       d=\"m 215.98949,804.88502 25.7387,1.3e-4\"\n",
    "       id=\"path11252\" />\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"153.68098\"\n",
    "       y=\"915.71051\"\n",
    "       id=\"text2711-6-2-9-2\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-84\"\n",
    "         x=\"153.68098\"\n",
    "         y=\"915.71051\"\n",
    "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">w</tspan></text>\n",
    "    <path\n",
    "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-37)\"\n",
    "       d=\"m 31.113403,791.97918 -1.3e-4,25.7387\"\n",
    "       id=\"path11252-5\" />\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"26.501303\"\n",
    "       y=\"780.6109\"\n",
    "       id=\"text2711-6-2-9-8\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-2\"\n",
    "         x=\"26.501303\"\n",
    "         y=\"780.6109\"\n",
    "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">g</tspan></text>\n",
    "    <rect\n",
    "       style=\"fill:#ffffff;fill-opacity:1;stroke:#000000;stroke-width:1;stroke-linecap:round;stroke-opacity:1\"\n",
    "       id=\"rect1007\"\n",
    "       width=\"59\"\n",
    "       height=\"59\"\n",
    "       x=\"130.5\"\n",
    "       y=\"792.86218\"\n",
    "       rx=\"0\"\n",
    "       ry=\"0\" />\n",
    "    <g\n",
    "       id=\"g1363\"\n",
    "       transform=\"translate(-6,20)\">\n",
    "      <path\n",
    "         style=\"fill:none;stroke:#ff0000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-9)\"\n",
    "         d=\"m 161.00001,831.69534 -45.73871,1.3e-4\"\n",
    "         id=\"path11252-4\" />\n",
    "      <path\n",
    "         style=\"fill:none;stroke:#0000ff;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-9-3)\"\n",
    "         d=\"m 160.79738,832.36215 -1.3e-4,-75.7387\"\n",
    "         id=\"path11252-4-6\" />\n",
    "    </g>\n",
    "    <path\n",
    "       style=\"fill:none;stroke:#000000;stroke-width:1.5;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#TriangleOutM-37-5)\"\n",
    "       d=\"m 159.99967,822.02879 3.4e-4,75.73871\"\n",
    "       id=\"path11252-5-0\" />\n",
    "    <text\n",
    "       xml:space=\"preserve\"\n",
    "       style=\"font-style:normal;font-weight:normal;font-size:18.6667px;line-height:1.25;font-family:sans-serif;fill:#000000;fill-opacity:1;stroke:none\"\n",
    "       x=\"85.624084\"\n",
    "       y=\"854.51099\"\n",
    "       id=\"text2711-6-2-9-8-4\"><tspan\n",
    "         sodipodi:role=\"line\"\n",
    "         id=\"tspan2709-5-9-2-2-1\"\n",
    "         x=\"85.624084\"\n",
    "         y=\"854.51099\"\n",
    "         style=\"font-style:italic;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:18.6667px;font-family:'Times New Roman';-inkscape-font-specification:'Times New Roman, '\">f<tspan\n",
    "   style=\"font-size:65%;baseline-shift:sub\"\n",
    "   id=\"tspan2197\">k</tspan></tspan></text>\n",
    "  </g>\n",
    "</svg>\n",
    "\n",
    "<br>\n",
    "\n",
    "Gambar <a name='fig2'>2</a>. Diagram gaya-gaya yang bekerja pada benda\n",
    "bermassa $m$."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a8ac2b2c",
   "metadata": {},
   "source": [
    "Terlihat bahwa pada arah $y$ terdapat gaya normal $N$ dan gaya gravitasi $w$, sedangkan pada arah $x$ hanya terdapat gaya gesek kinetis $f_k$ yang melawan arah gerak benda. Arah gerak benda diberikan oleh arah kecepatan $v$."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "23119498",
   "metadata": {},
   "source": [
    "## Metode numerik\n",
    "Interasi suatu fungsi $f(x)$ berbentuk\n",
    "\n",
    "<a name='eqn8'></a>\n",
    "\\begin{equation}\\label{eqn:integral-1}\\tag{8}\n",
    "A = \\int_a^b f(x) dx\n",
    "\\end{equation}\n",
    "\n",
    "dapat didekati dengan\n",
    "\n",
    "<a name='eqn9'></a>\n",
    "\\begin{equation}\\label{eqn:integral-2}\\tag{9}\n",
    "A \\approx \\sum_{i = 0}^N f\\left[ \\tfrac12(x_i + x_{i+1}) \\right] \\Delta x\n",
    "\\end{equation}\n",
    "\n",
    "yang dikenal sebagai metode persegi titik tengah, di mana\n",
    "\n",
    "<a name='eqn10'></a>\n",
    "\\begin{equation}\\label{eqn:integral-3}\\tag{10}\n",
    "\\Delta x = \\frac{b - a}{N}\n",
    "\\end{equation}\n",
    "\n",
    "dengan $N$ adalah jumlah partisi. Variabel $x_i$ pada Persamaan ([9](#eqn9)) diberikan oleh\n",
    "\n",
    "<a name='eqn11'></a>\n",
    "\\begin{equation}\\label{eqn:integral-4}\\tag{11}\n",
    "x_i = a + i\\Delta x\n",
    "\\end{equation}\n",
    "\n",
    "dengan $i = 0, \\dots, N$."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d82ae009",
   "metadata": {},
   "source": [
    "## Penyelesaian\n",
    "Penerapan Persamaan ([1](#eqn1)), ([2](#eqn2)), ([3](#eqn3)), ([4](#eqn4)), dan ([5](#eqn5)) pada Gambar [2](#fig2) akan menghasilkan\n",
    "\n",
    "<a name='eqn10'></a>\n",
    "\\begin{equation}\\label{eqn:friction}\\tag{10}\n",
    "f_k = \\mu_k mg\n",
    "\\end{equation}\n",
    "\n",
    "dan usahanya adalah\n",
    "\n",
    "<a name='eqn11'></a>\n",
    "\\begin{equation}\\label{eqn:friction-work}\\tag{11}\n",
    "\\begin{array}{rcl}\n",
    "W & = & \\displaystyle \\int_{x_0}^x f_k dx \\newline\n",
    "& = & \\displaystyle \\int_{x_0}^x \\mu_k m g dx \\newline\n",
    "& = & \\displaystyle m g \\int_{x_0}^x \\mu_k dx\n",
    "\\end{array}\n",
    "\\end{equation}\n",
    "\n",
    "dengan koefisien gesek statisnya dapat merupakan fungsi dari posisi $\\mu_k = \\mu_k(x)$."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "33c63a26",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<div>\n",
       "Gambar <a name='fig3'>3</a>. Kurva antara usaha $W$ dan jarak tempuh $x - x_0$.\n",
       "</div>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXgAAAEKCAYAAAAYd05sAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAP60lEQVR4nO3df2xd91nH8c9njlnv2moexHSNUwhCyBI0bA5WVdSpKh2du7XqrNA/irSNDkEETKMTkysCiIqBiISlabAJpqgdbKxlqzLXlGqtV9SWaRILOHWZu2Zm1dRqdTrFLXJ/wNWWuA9/3JM0cZ3YN7nfe+zH75dk9frck/t9dBq/c33u8bUjQgCAfN5U9wAAgDIIPAAkReABICkCDwBJEXgASIrAA0BSW+oe4FRbt26NHTt21D0GAGwYhw4deiEi+le6b10FfseOHZqenq57DADYMGw/e6b7OEUDAEkReABIisADQFIEHgCSKvoiq+0+SXdKulxSSPrNiPj3kmsCwEYxOTOv8ak5HVlsaltfQ2MjgxodGujY45e+iuavJT0UETfb/jFJbym8HgBsCJMz89o7MavmsSVJ0vxiU3snZiWpY5EvdorG9lslXS3pLkmKiB9FxGKp9QBgIxmfmjsZ9xOax5Y0PjXXsTVKnoP/GUkLkv7e9oztO21fuHwn23tsT9ueXlhYKDgOAKwfRxabbW0/FyUDv0XSLkl/FxFDkv5X0h8u3yki9kfEcEQM9/ev+MNYAJDOtr5GW9vPRcnAPyfpuYg4WH1+QK3gA8CmNzYyqEZvz2nbGr09GhsZ7NgaxQIfET+Q9H3bJ6Z9t6SnSq0HABvJ6NCA9u3eqYG+hixpoK+hfbt3bqiraD4q6e7qCprvSfpw4fUAYMMYHRroaNCXKxr4iHhC0nDJNQAAK+MnWQEgKQIPAEkReABIisADQFIEHgCSIvAAkBSBB4CkCDwAJEXgASApAg8ASRF4AEiKwANAUgQeAJIi8ACQFIEHgKQIPAAkReABICkCDwBJEXgASIrAA0BSBB4AkiLwAJAUgQeApAg8ACRF4AEgKQIPAEkReABIisADQFIEHgCSIvAAkBSBB4CktpR8cNvPSHpF0pKk4xExXHI9APWanJnX+NScjiw2ta2vobGRQY0ODdQ91qZVNPCVX4mIF7qwDoAaTc7Ma+/ErJrHliRJ84tN7Z2YlSQiXxNO0QDoiPGpuZNxP6F5bEnjU3M1TYTSgQ9JX7N9yPaelXawvcf2tO3phYWFwuMAKOXIYrOt7SivdODfFRG7JL1X0kdsX718h4jYHxHDETHc399feBwApWzra7S1HeUVDXxEzFf/PSrpPklXlFwPQH3GRgbV6O05bVujt0djI4M1TYRigbd9oe2LT9yW9B5JT5ZaD0C9RocGtG/3Tg30NWRJA30N7du9kxdYa1TyKppLJN1n+8Q690TEQwXXA1Cz0aEBgr6OFAt8RHxP0jtKPT4A4Oy4TBIAkiLwAJAUgQeApAg8ACRF4AEgKQIPAEkReABIisADQFIEHgCSIvAAkBSBB4CkCDwAJEXgASApAg8ASRF4AEiKwANAUgQeAJIi8ACQFIEHgKQIPAAkReABICkCDwBJEXgASIrAA0BSBB4AkiLwAJAUgQeApAg8ACRF4AEgKQIPAEkVD7ztHtszth8ovRYA4HXdeAZ/m6TDXVgHAHCKooG3vV3SDZLuLLkOAOCNSj+D/5Sk2yW9VngdAMAyxQJv+0ZJRyPi0Cr77bE9bXt6YWGh1DgAsOmUfAZ/laSbbD8j6UuSrrX9xeU7RcT+iBiOiOH+/v6C4wDA5lIs8BGxNyK2R8QOSbdIeiQiPlBqPQDA6bgOHgCS2tKNRSLiMUmPdWMtAEALz+ABICkCDwBJEXgASIrAA0BSBB4AkiLwAJAUgQeApAg8ACRF4AEgKQIPAEkReABIisADQFIEHgCSWjXwtj9q+23dGAYA0DlreQZ/iaT/tH2v7ettu/RQAIDzt2rgI+JPJP2cpLsk3Srpu7b/0vbPFp4NAHAe1nQOPiJC0g+qj+OS3ibpgO2/KjgbAOA8rPobnWzfJulDkl6QdKeksYg4ZvtNkr4r6fayIwIAzsVafmXfj0vaHRHPnroxIl6zfWOZsQAA52vVwEfEHWe573BnxwEAdArXwQNAUgQeAJIi8ACQFIEHgKQIPAAkReABICkCDwBJEXgASIrAA0BSBB4AkiLwAJDUWt5s7JzYvkDS1yW9uVrnwNne1wZYjyZn5jU+Nacji01t62tobGRQo0MDdY8FrEmxwEv6oaRrI+JV272SvmH7wYj4ZsE1gY6ZnJnX3olZNY8tSZLmF5vaOzErSUQeG0KxUzTR8mr1aW/1EaXWAzptfGruZNxPaB5b0vjUXE0TAe0peg7edo/tJyQdlfRwRBxcYZ89tqdtTy8sLJQcB2jLkcVmW9uB9aZo4CNiKSLeKWm7pCtsX77CPvsjYjgihvv7+0uOA7RlW1+jre3AetOVq2giYlHSo5Ku78Z6QCeMjQyq0dtz2rZGb4/GRgZrmghoT7HA2+633Vfdbki6TtJ3Sq0HdNro0ID27d6pgb6GLGmgr6F9u3fyAis2jJJX0Vwq6fO2e9T6h+TeiHig4HpAx40ODRB0bFjFAh8R35I0VOrxAQBnx0+yAkBSBB4AkiLwAJAUgQeApAg8ACRF4AEgKQIPAEkReABIisADQFIEHgCSIvAAkBSBB4CkCDwAJEXgASApAg8ASRF4AEiKwANAUgQeAJIi8ACQFIEHgKQIPAAkReABICkCDwBJEXgASIrAA0BSBB4AkiLwAJAUgQeApAg8ACRF4AEgqWKBt32Z7UdtP2X727ZvK7UWAOCNthR87OOSPh4Rj9u+WNIh2w9HxFMF18QqJmfmNT41pyOLTW3ra2hsZFCjQwN1jwWggGKBj4jnJT1f3X7F9mFJA5IIfE0mZ+a1d2JWzWNLkqT5xab2TsxKEpEHEurKOXjbOyQNSTrYjfWwsvGpuZNxP6F5bEnjU3M1TQSgpOKBt32RpK9I+lhEvLzC/XtsT9ueXlhYKD3OpnZksdnWdgAbW9HA2+5VK+53R8TESvtExP6IGI6I4f7+/pLjbHrb+hptbQewsZW8isaS7pJ0OCI+WWodrN3YyKAavT2nbWv09mhsZLCmiQCUVPIZ/FWSPijpWttPVB/vK7geVjE6NKB9u3dqoK8hSxroa2jf7p28wAokVfIqmm9IcqnHx7kZHRog6MAmwU+yAkBSBB4AkiLwAJAUgQeApAg8ACRF4AEgKQIPAEkReABIisADQFIEHgCSIvAAkBSBB4CkCDwAJEXgASApAg8ASRF4AEiKwANAUgQeAJIi8ACQFIEHgKQIPAAkReABICkCDwBJEXgASIrAA0BSBB4AkiLwAJAUgQeApAg8ACRF4AEgKQIPAEltKfXAtj8n6UZJRyPi8lLrTM7Ma3xqTkcWm9rW19DYyKBGhwZKLQcAG0bJZ/D/IOn6go+vyZl57Z2Y1fxiUyFpfrGpvROzmpyZL7ksAGwIxQIfEV+X9D+lHl+Sxqfm1Dy2dNq25rEljU/NlVwWADaE2s/B295je9r29MLCQlt/9shis63tALCZ1B74iNgfEcMRMdzf39/Wn93W12hrOwBsJrUH/nyMjQyq0dtz2rZGb4/GRgZrmggA1o9iV9F0w4mrZbiKBgDeqORlkv8k6RpJW20/J+mOiLir0+uMDg0QdABYQbHAR8Svl3psAMDqNvQ5eADAmRF4AEiKwANAUgQeAJJyRNQ9w0m2FyQ9e45/fKukFzo4TqcwV3uYqz3M1Z6Mc/10RKz4U6LrKvDnw/Z0RAzXPcdyzNUe5moPc7Vns83FKRoASIrAA0BSmQK/v+4BzoC52sNc7WGu9myqudKcgwcAnC7TM3gAwCkIPAAktaECb/tzto/afvIM99v239h+2va3bO9aJ3NdY/sl209UH3/apbkus/2o7adsf9v2bSvs0/Vjtsa5un7MbF9g+z9s/1c115+tsM+bbX+5Ol4Hbe9YJ3PdanvhlOP1W6XnOmXtHtszth9Y4b6uH681zlXL8bL9jO3Zas3pFe7v7NdjRGyYD0lXS9ol6ckz3P8+SQ9KsqQrJR1cJ3NdI+mBGo7XpZJ2VbcvlvTfkn6+7mO2xrm6fsyqY3BRdbtX0kFJVy7b5/ckfba6fYukL6+TuW6V9Jlu/x2r1v4DSfes9P+rjuO1xrlqOV6SnpG09Sz3d/TrcUM9g4/Vf5H3+yV9IVq+KanP9qXrYK5aRMTzEfF4dfsVSYclLX/z/K4fszXO1XXVMXi1+rS3+lh+FcL7JX2+un1A0rttex3MVQvb2yXdIOnOM+zS9eO1xrnWq45+PW6owK/BgKTvn/L5c1oH4aj8cvUt9oO2f6Hbi1ffGg+p9ezvVLUes7PMJdVwzKpv65+QdFTSwxFxxuMVEcclvSTpJ9bBXJL0a9W39QdsX1Z6psqnJN0u6bUz3F/L8VrDXFI9xyskfc32Idt7Vri/o1+P2QK/Xj2u1vtFvEPSpyVNdnNx2xdJ+oqkj0XEy91c+2xWmauWYxYRSxHxTknbJV1h+/JurLuaNcz1L5J2RMQvSnpYrz9rLsb2jZKORsSh0mu1Y41zdf14Vd4VEbskvVfSR2xfXXKxbIGfl3Tqv8Tbq221ioiXT3yLHRFfldRre2s31rbdq1ZE746IiRV2qeWYrTZXncesWnNR0qOSrl9218njZXuLpLdKerHuuSLixYj4YfXpnZJ+qQvjXCXpJtvPSPqSpGttf3HZPnUcr1Xnqul4KSLmq/8elXSfpCuW7dLRr8dsgb9f0oeqV6KvlPRSRDxf91C2337ivKPtK9Q67sWjUK15l6TDEfHJM+zW9WO2lrnqOGa2+233Vbcbkq6T9J1lu90v6Teq2zdLeiSqV8fqnGvZedqb1Hpdo6iI2BsR2yNih1ovoD4SER9YtlvXj9da5qrjeNm+0PbFJ25Leo+k5VfedfTrsdjvZC3BK/wib7VecFJEfFbSV9V6FfppSf8n6cPrZK6bJf2u7eOSmpJuKf2XvHKVpA9Kmq3O30rSH0n6qVNmq+OYrWWuOo7ZpZI+b7tHrX9Q7o2IB2x/QtJ0RNyv1j9M/2j7abVeWL+l8Exrnev3bd8k6Xg1161dmGtF6+B4rWWuOo7XJZLuq563bJF0T0Q8ZPt3pDJfj7xVAQAkle0UDQCgQuABICkCDwBJEXgASIrAA0BSBB4AktpQ18ED6131Ayx/K+lHkh6LiLtrHgmbGM/ggc7aLelARPy2Wj8hCdSGwAOdtV2vvxvgUp2DAAQem45bv03quur2X9j+dAcf5zm1Ii/x9YWacQ4em9Edkj5h+yfVei/6cz2VstLjXCDpM7ZvUOstaYHa8F402JRs/5ukiyRdU/1WqVPv+1dJb1/hj/1xRPzzWh8HqBvP4LHp2N6p1js0vrhSlCPiVzvxOEDdOEeITaV6H/C71frdl6/aXv4LPbr6OEBJBB6bhu23SJqQ9PGIOCzpz9U6j17L4wClcQ4eAJLiGTwAJEXgASApAg8ASRF4AEiKwANAUgQeAJIi8ACQFIEHgKQIPAAk9f92i6o+KZldAgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "plt.ion()\n",
    "\n",
    "# set integral lower and upper bounds\n",
    "a = 0\n",
    "b = 1\n",
    "\n",
    "# generate x\n",
    "x = [1, 2, 3, 4, 5]\n",
    "\n",
    "# generate y from numerical integration\n",
    "y = [1, 2, 3, 5, 6]\n",
    "\n",
    "## plot results\n",
    "fig, ax = plt.subplots()\n",
    "ax.scatter(x, y)\n",
    "ax.set_xlabel(\"$x - x^0$\")\n",
    "ax.set_ylabel(\"y\")\n",
    "\n",
    "from IPython import display\n",
    "from IPython.core.display import HTML\n",
    "HTML('''\n",
    "<div>\n",
    "Gambar <a name='fig3'>3</a>. Kurva antara usaha $W$ dan jarak tempuh $x - x_0$.\n",
    "</div>\n",
    "''')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6f0ceb31",
   "metadata": {},
   "source": [
    "## Diskusi\n",
    "Berdasarkan Gambar [3](#fig3) dapat dijelaskan bahwa dengan $\\mu_k = \\mu_k(x)$ maka kurva $W(x)$ tidak lagi linier karena dipengaruhi oleh sejauh mana perhitungan kerja dilakukan."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "67fba2fe",
   "metadata": {},
   "source": [
    "## Kesimpulan\n",
    "Perhitungan kerja dengan $\\mu_k = \\mu_k(x)$ telah dapat dilakukan."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "44995bd5",
   "metadata": {},
   "source": [
    "## Referensi\n",
    "1. J. A. C. Martins, J. T. Oden, F. M. F. Simões, \"A study of static and kinetic friction\", International Journal of Engineerting Science, vol 28, no 1, p 29-92, 1990, url <https://doi.org/10.1016/0020-7225(90)90014-A>. \n",
    "1. Carl Rod Nave, \"Friction\", HyperPhysics, 2017, url <http://hyperphysics.phy-astr.gsu.edu/hbase/frict.html#fri> [20220419].\n",
    "2. Wikipedia contributors, \"Friction\", Wikipedia, The Free Encyclopedia, 12 April 2022, 00:33 UTC, url <https://en.wikipedia.org/w/index.php?oldid=1082223658> [20220419].\n",
    "3. Tia Ghose, Ailsa Harvey, \"What is friction?\", Live Science, 8 Feb 2022, url <https://www.livescience.com/37161-what-is-friction.html> [20220419]."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7da2b33",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
